language: node_js
node_js:
  - 0.8
env:
  global:
    - secure: "C1+k93MqoB2wD0VJbH5afLJq9SZ4rlb9VQVE4uzSZHkx1zp7+7bgftDfCxm+\nrHHWfXTTj0MK1H12m7URxkqGcV7jmnOMaSMakaDbn/K70W/ap9zqFNmRfClJ\nMztcFkGXzLMHje24z1UOM8967b26D6S1J/1vFQ8YgcfzLprePDA="
    - secure: "UVWP1Oywk/27zk5MhWmPjJsGqW6uIMjAcYIj+vlIV9GKWwek1MIP4OctcwvA\n7e82HkQv+WQrAP8xF+LJGU0JVm+M1agqO5MO/KXlGpJDkbubC3X9FGnaHoXP\nl5jtTHzAaqmWNnI1SR8O680mh7DmqjYw6NMQFPu+5gCJhMr1Mg4="
