language: node_js
node_js:
  - 0.8
env:
  global:
    - secure: "BuhpWxstUJ4S6V1KOwQQYIgNSnWObifiPiGGndWnlJQ4zEctxwCtZlBJZG73\nNwywyiHphtvJQOOnaVoHr6WUWCVEGvzESK/+XdUg7MuQ9gB2RMz6SpcM7mji\nzCa5iHxqMUd8spkraYtWqBOvvaOivzypuB7KTleD6AtcjLybUV4="
